language: node_js
sudo: required
dist: xenial
node_js: stable
install:
  - npm install
branches:
  only:
    - master
before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install hexo-deployer-git --save
  - npm install hexo-wordcount --save
  - npm install hexo-generator-searchdb --save
  - sudo apt-get install libpng16-dev

install:
  - npm install

script:
  - hexo clean
  - hexo g
  - hexo d