language: node_js
sudo: required
dist: xenial
node_js: stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - sudo apt-get install libpng16-dev
install:
  - npm install
script:
  - hexo clean
  - hexo g
  - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
  - hexo d