language: node_js
sudo: required
dist: xenial
node_js: stable
install:
  - npm install
branches:
  only:
    - master
before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - sudo apt-get install libpng16-dev

install:
  - npm install

script:
  - hexo clean
  - hexo g
after_success:
  - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
  - hexo d